app = 'wppconnect-server-polished-grass-7184'
primary_region = 'eze'

[build]

[deploy]
  strategy = "rolling"

[http_service]
  internal_port = 21465
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
  memory = "8gb"
  cpu_kind = "performance"  
  cpus = 2    

[mounts]
  source = "whatsapp_data"
  destination = "/data"

[env]
  SESSION_FOLDER = "/data"
  CUSTOM_USER_DATA_DIR = "/data/userData/"
  TOKEN_STORE_TYPE = "file"
  NODE_ENV = "production"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
  DISPLAY = ":99"
  PUPPETEER_HEADLESS = "true"
  CHROME_NO_SANDBOX = "true"
  WPPCONNECT_NO_SANDBOX = "true"
  WPPCONNECT_HEADLESS = "true"
  CHROME_BIN = "/usr/bin/chromium-browser"
  PUPPETEER_SKIP_CHROMIUM_DOWNLOAD = "true"
  CHROME_PATH = "/usr/bin/chromium-browser"
  DNS_SERVERS = "8.8.8.8,8.8.4.4"
  HTTP_PROXY = ""
  HTTPS_PROXY = ""
