app = 'wppconnect-server-polished-grass-7184'
primary_region = 'eze'

[build]

[deploy]
  strategy = "immediate"

[http_service]
  internal_port = 21465
  force_https = true
  auto_start_machines = true
  min_machines_running = 1
  max_machines_running = 1
  processes = ['app']

[[vm]]
memory = "8gb"
cpu_kind = "performance"  
cpus = 2    

[mounts]
  source = "whatsapp_data"
  destination = "/data"

[env]
  SESSION_FOLDER = "/data"
  CUSTOM_USER_DATA_DIR = "/data/userData/"
  TOKEN_STORE_TYPE = "file"
  NODE_ENV = "production"
  PUPPETEER_EXECUTABLE_PATH = "/usr/bin/chromium-browser"
  DISPLAY = ":99"
  PUPPETEER_HEADLESS = "true"
  CHROME_NO_SANDBOX = "true"
